### ISSUE TITLE
The option 'best' is missing

### ISSUE THREAD

**Issue by mohan-raj** [gabrielecirulli/hn-special#114] opened 2016-12-29 13:06 UTC
### Steps to reproduce this issue

1. 
2. 
3.

**Comment by PxlBuzzard** [comment] 2017-02-07 05:57
This is a reasonable request. The problem is that the top bar is already at maximum capacity for text on a single row. If you have a name longer than ~14 characters it creates a second row that the extension doesn't really account for visually. There are multiple ways to solve it, but someone needs to put a little time into the top bar to make this request work best.

**Comment by PxlBuzzard** [comment] 2017-02-08 03:16
I realized this is a dupe of #90, I will close this one.

**Closed by PxlBuzzard** 2017-02-08 03:16 UTC
