### ISSUE TITLE
Menu is not hiding

### ISSUE THREAD

**Issue by FranciscoG** [gabrielecirulli/hn-special#101] opened 2016-07-27 18:14 UTC
Editing to follow rules of bug reporting:

### Steps to reproduce this issue

1. Turn Visual Theme OFF

### Expected result
Header/nav reverts back to original style

### Actual result
The HN-Special menu does not hide and expands the the header

### Notes and screenshots
Chrome 51.0.2704.103 (64-bit)
OSX 10.11.2

![http://i.imgur.com/JnTtpRH.png](http://i.imgur.com/JnTtpRH.png)

**Comment by FranciscoG** [comment] 2016-07-27 18:16
Chrome just updated, now on version Version 52.0.2743.82 (64-bit)
still happening

**Comment by gabrielecirulli** [comment] 2016-07-27 18:47
Thanks for reporting. Duplicate of https://github.com/gabrielecirulli/hn-special/issues/94.

**Comment by FranciscoG** [comment] 2016-07-27 18:52
oops did not see your original issue, sorry about that

**Closed** 2016-07-30 19:17 UTC
Labels: Duplicate
