### ISSUE TITLE
Feature Request: Change text box color

### ISSUE THREAD

**Issue by zfrenchee** [gabrielecirulli/hn-special#115] opened 2017-01-13 20:32 UTC
First off, thank you for making HN Special. It's fantastic and I love it. A suggestion for how to improve it: 

<img width="903" alt="screen shot 2017-01-13 at 11 23 57 am" src="https://cloud.githubusercontent.com/assets/2761597/21944645/4badb6ca-d9a5-11e6-83ed-2e0315bc12ea.png">

As you can see above, the text box is gray, which implies its inactive, but tbhat's not the case, it's active. I believe this is either confusing or ugly for most people, and probably a very easy fix?

**Comment by PxlBuzzard** [comment] 2017-02-07 07:21
Duplicate of #99. Fixed in the next version :)

**Closed by PxlBuzzard** 2017-02-07 07:21 UTC
