### ISSUE TITLE
Top Header Broken as of 14/03/2018

### ISSUE THREAD

**Issue by JeffreyCA** [gabrielecirulli/hn-special#118] opened 2018-03-14 18:38 UTC
### Steps to reproduce this issue

1. 
2. 
3. 

### Expected result
![screenshot1](https://user-images.githubusercontent.com/9157833/37423931-7d1a7ab0-2795-11e8-8b7e-2495551bcb8a.png)

### Actual result
<img width="917" alt="screen shot 2018-03-14 at 2 37 44 pm" src="https://user-images.githubusercontent.com/9157833/37423865-509ebf3c-2795-11e8-9ffd-c0099a44ccaa.png">

**Comment by PxlBuzzard** [comment] 2018-03-14 20:38
Closed as a dupe of #81.

**Closed by PxlBuzzard** 2018-03-14 20:38 UTC
