### ISSUE TITLE
Dark Theme along with High Contrast needs new voting buttons (and possibly other style changes)

### ISSUE THREAD

**Issue by floydpink** [gabrielecirulli/hn-special#111] opened 2016-11-03 13:48 UTC
### Steps to reproduce this issue

1. Enable "Dark Theme"
2. Enable "High contrast"
3. Notice how the voting buttons are "invisible" now

### Expected result
 - The voting buttons should still be visible/usable
 - The page background should be dark (?)

### Actual result
 - Voting buttons are not seen because of their color being the same as page background color
 - Page background is not dark

### Notes and screenshots
Not sure if this is just my machine/browser/other-addons

**Comment by PxlBuzzard** [comment] 2017-02-08 02:59
Duplicate of #97

**Closed by PxlBuzzard** 2017-02-08 02:59 UTC
